## Imports

In [3]:
from vizdoom import DoomGame
import random
import time
import numpy as np

## Test Doom Environment

In [13]:
def test_environment():
    game = DoomGame()
    game.load_config("basic.cfg")
    game.set_doom_scenario_path("basic.wad")
    game.init()
    shoot = [0, 0, 1]
    left = [1, 0, 0]
    right = [0, 1, 0]
    actions = [shoot, left, right]

    episodes = 2
    for i in range(episodes):
        game.new_episode()
        while not game.is_episode_finished():
            state = game.get_state()
            img = state.screen_buffer
            misc = state.game_variables
            action = random.choice(actions)
            print(action)
            reward = game.make_action(action)
            print ("\treward:", reward)
            time.sleep(0.02)
        print ("Result:", game.get_total_reward())
        time.sleep(2)
    game.close()
    
test_environment()

[1, 0, 0]
	reward: -1.0
[0, 0, 1]
	reward: -1.0
[0, 1, 0]
	reward: -1.0
[0, 0, 1]
	reward: -1.0
[1, 0, 0]
	reward: -1.0
[0, 0, 1]
	reward: 100.0
[0, 1, 0]
	reward: -1.0
Result: 94.0
[1, 0, 0]
	reward: -1.0
[1, 0, 0]
	reward: -1.0
[1, 0, 0]
	reward: -1.0
[1, 0, 0]
	reward: -1.0
[0, 0, 1]
	reward: -1.0
[0, 0, 1]
	reward: -1.0
[1, 0, 0]
	reward: -1.0
[1, 0, 0]
	reward: -1.0
[1, 0, 0]
	reward: 100.0
[1, 0, 0]
	reward: -1.0
Result: 91.0


## We create the environment

In [14]:
class DoomEnv():
    
    def __init__(self):
        # Create the environment
        self.game = DoomGame()
        
        # Load the config
        self.game.load_config('basic.cfg')
        
        # Load the scenario
        self.game.set_doom_scenario_path('basic.wad')
        self.game.init()
        
        # Create possible actions [left, right, shoot]
        self.actions = [[1, 0, 0],
                        [0, 1, 0],
                        [0, 0, 1]]
        
        # Number of tics we skip for each action
        self.skip_rate = 4
        
    def preprocess_frame(self, frame):
        return frame
    
    def run_game(self, nb_episode=2):
        for i in range(nb_episode):
            # Start new episode
            self.game.new_episode()
            
            while not self.game.is_episode_finished():
                state = self.game.get_state()
                
                # Get image
                img = state.screen_buffer
                
                var = state.game_variables
                print(var)
                
                action = random.choice(self.actions)
                print(action)
                
                reward = self.game.make_action(action, self.skip_rate)
                print ("\treward:", reward)
                
                time.sleep(0.1)
            print ("Result:", self.game.get_total_reward())
            time.sleep(2)
            
        self.game.close()
        
d = DoomEnv()
d.run_game()

[50.]
[0, 0, 1]
	reward: -4.0
[50.]
[0, 1, 0]
	reward: 99.0
Result: 95.0
[50.]
[0, 1, 0]
	reward: -4.0
[50.]
[0, 0, 1]
	reward: -4.0
[50.]
[1, 0, 0]
	reward: -9.0
[49.]
[0, 1, 0]
	reward: -4.0
[49.]
[0, 0, 1]
	reward: -4.0
[49.]
[0, 1, 0]
	reward: -9.0
[48.]
[0, 0, 1]
	reward: -4.0
[48.]
[1, 0, 0]
	reward: -4.0
[48.]
[0, 0, 1]
	reward: -4.0
[48.]
[1, 0, 0]
	reward: -9.0
[47.]
[0, 1, 0]
	reward: -4.0
[47.]
[0, 0, 1]
	reward: -4.0
[47.]
[0, 1, 0]
	reward: -9.0
[46.]
[0, 0, 1]
	reward: -4.0
[46.]
[1, 0, 0]
	reward: -4.0
[46.]
[0, 0, 1]
	reward: -4.0
[46.]
[0, 1, 0]
	reward: -9.0
[45.]
[0, 0, 1]
	reward: -4.0
[45.]
[1, 0, 0]
	reward: -4.0
[45.]
[0, 0, 1]
	reward: -4.0
[45.]
[1, 0, 0]
	reward: -9.0
[44.]
[0, 0, 1]
	reward: -4.0
[44.]
[0, 0, 1]
	reward: -4.0
[44.]
[0, 0, 1]
	reward: -4.0
[44.]
[0, 0, 1]
	reward: -9.0
[43.]
[0, 0, 1]
	reward: -4.0
[43.]
[0, 0, 1]
	reward: -4.0
[43.]
[1, 0, 0]
	reward: -9.0
[42.]
[1, 0, 0]
	reward: -4.0
[42.]
[0, 1, 0]
	reward: -4.0
[42.]
[0, 1, 0]
	reward: -4

In [7]:
a = np.zeros((4, 5, 5))
a

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [8]:
b = np.ones((5, 5))
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
a[0, :, :] = b
a

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])